module "kubernetes" {
  source = "./modules/gke"
  project-id = "capable-argon-300716"
  region = "europe-west1"
  # gke-name =
  # description =
  # gke-version =
  # gke-zone =
  # gke-additional-zones =
  # gke-certificate-enabled =
  # gke-node-pool-name =
  # gke-initial-node-count =
  # gke-node-disk-size =
  # gke-node-disk-type =
  # gke-node-image =
  # gke-node-machine-type =
  # gke-node-preemtible-enabled =
  # project_name =
  # stages =
  # gke-autoscaling-min =
  # gke-autoscaling-max =
  # gke-node-auto-repair-enabled =
  # gke-node-auto-upgrade-enabled =
  # gke-node-lb-disabled =
  # gke-node-pods-autoscaling-disabled =
  # gke-node-dashboard-disabled =
  # gke-node-network-policy-disabled =
}