---
- name: install nginx
  become: yes
  become_method: sudo
  yum: name=nginx state=present

- name: Copy default site file
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Copy nginx file
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy well-known file
  template: src=le-well-known.conf dest=/etc/nginx/default.d/le-well-known.conf
  notify: restart nginx
