---

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
  when: admin_password.stat.exists == true

- name: Wait for the Jenkins password
  wait_for:
    path: /var/lib/jenkins/secrets/initialAdminPassword
  become: true

- name: Read the Jenkins password
  slurp:
    src: /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkinsPassword

- name: display post install message
  debug:
    msg:
      - 'Everything is installed. Use this password to login on jenkins:'
      - "{{ jenkinsPassword['content'] | b64decode | trim }}"
